steps:
  - label: "Update Test Ownership?"
    branches: "main"
    plugins:
      - monorepo-diff#v1.0.1:
          watch:
            - path: ./TESTOWNERS
              config:
                trigger: update-test-ownership
