#!/bin/bash

set -e

docker build -t app --load .
docker run \
  --env API_ACCESS_TOKEN \
  -v $(pwd):/app \
  -it --rm app sh -c "bin/fetch_timing_data.rb"

buildkite-agent artifact upload timings.csv
buildkite-agent artifact upload annotation.md
cat annotation.md | buildkite-agent annotate

