#!/bin/bash

set -e

export API_ACCESS_TOKEN=$(buildkite-agent secret get API_ACCESS_TOKEN)

docker build -t app --load .
docker run \
  --env API_ACCESS_TOKEN \
  -v $(pwd):/app \
  -it --rm app sh -c "bin/fetch_skipped_tests.rb"

buildkite-agent artifact upload skipped.json
cat skipped.json | buildkite-agent annotate
