#!/bin/bash

set -e

docker build -t app --load .
docker run \
  --env BUILDKITE_ANALYTICS_TOKEN \
  --env BUILDKITE_BUILD_ID \
  --env BUILDKITE_BUILD_NUMBER \
  --env BUILDKITE_JOB_ID \
  --env BUILDKITE_BRANCH \
  --env BUILDKITE_COMMIT \
  --env BUILDKITE_MESSAGE \
  --env BUILDKITE_BUILD_URL \
  --env BUILDKITE_PARALLEL_JOB \
  --env BUILDKITE_PARALLEL_JOB_COUNT \
  --env BUILDKITE_SPLITTER_TEST_FILE_PATTERN \
  --env BUILDKITE_SPLITTER_IDENTIFIER \
  -it --rm app sh -c "test-splitter"
