#!/bin/bash

set -e

buildkite-agent artifact download skipped.json .

export BUILDKITE_ANALYTICS_TOKEN=$(buildkite-agent secret get SUITE_TOKEN)
export BUILDKITE_SPLITTER_API_ACCESS_TOKEN=$(buildkite-agent secret get API_ACCESS_TOKEN)
export BUILDKITE_ORGANIZATION_SLUG="test-analytics-sandbox"
export BUILDKITE_SPLITTER_SUITE_SLUG="rspec-example"
export BUILDKITE_SPLITTER_TEST_CMD="bundle exec rspec {{testExamples}} --tag ~@quarantine"
export BUILDKITE_SPLITTER_DEBUG_ENABLED="true"

docker build -t app --load .
docker run \
  --env BUILDKITE_SPLITTER_DEBUG_ENABLED \
  --env BUILDKITE_SPLITTER_TEST_CMD \
  --env BUILDKITE_ANALYTICS_TOKEN \
  --env BUILDKITE_ORGANIZATION_SLUG \
  --env BUILDKITE_SPLITTER_SUITE_SLUG \
  --env BUILDKITE_SPLITTER_API_ACCESS_TOKEN \
  --env BUILDKITE_BUILD_ID \
  --env BUILDKITE_STEP_ID \
  --env BUILDKITE_BUILD_NUMBER \
  --env BUILDKITE_JOB_ID \
  --env BUILDKITE_BRANCH \
  --env BUILDKITE_COMMIT \
  --env BUILDKITE_MESSAGE \
  --env BUILDKITE_BUILD_URL \
  --env BUILDKITE_PARALLEL_JOB \
  --env BUILDKITE_PARALLEL_JOB_COUNT \
  --env BUILDKITE_SPLITTER_TEST_FILE_PATTERN \
  -it --rm app sh -c "test-splitter"
