#!/bin/bash

set -e

curl --location 'https://analytics-api.buildkite.com/v1/test-ownerships' \
     --header "Authorization: Bearer ${BUILDKITE_ANALYTICS_TOKEN}" \
     -F 'file=@./.buildkite/TESTOWNERS'
